@url = http://localhost:3030

GET {{url}}/accountOwner

###

POST {{url}}/accountOwner
Content-Type: application/json

{
    "firstName": "Doechii",
    "lastName": "New",
    "email": "crazy@live.com",
    "password": "dancingqueenisdancing"
}

###

POST  {{url}}/login
Content-Type: application/json

{
    "email": "crazy@live.com",
    "password": "dancingqueenisdancing"
}
