@url = http://localhost:3030

GET {{url}}/accountOwner

###

POST {{url}}/accountOwner
Content-Type: application/json

{
    "firstName": "Doechii",
    "lastName": "New",
    "email": "goingcrazy@live.com",
    "primaryAddress": {"street": "172 Clarkson Ave",
                        "city": "Brooklyn",
                        "zipcode": "11348",
                        "country": "United States"
    },
    "password": "dancingqueenisdancing"
}

###

POST  {{url}}/login
Content-Type: application/json

{
    "email": "goingcrazy@live.com",
    "password": "dancingqueenisdancing"
}

###

GET {{url}}/account/

###
POST {{url}}/account
Content-Type: application/json

{
    "accountOwner": "62cff187b5ea7c0b9cb25af8",
    "accountCurrency": "EUR",
    "accountType": "checking",
    "accountBalance": 132
    
}

###

PUT {{url}}/account/
Content-Type: application/json

